name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.5

dependencies:
  cached_network_image: ^4.0.4
  dio: ^5.11.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_gettext: ^2.3.0
  flutter_riverpod: ^3.4.3
  flutter_svg: ^2.3.0
  go_router: ^18.0.2
  google_fonts: ^9.0.0
  riverpod_annotation: ^4.0.7
  shared_preferences: ^2.5.6
  skeletonizer: ^3.0.0
  slide_to_act: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5
  fake_async: ^1.3.3
  build_runner: ^2.4.9
  riverpod_generator: ^4.0.9
  
dependency_overrides:
  analyzer: 14.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/language/
    - .env