import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const source = ['.env', '.env.template'].find(existsSync);
if (!source) {
  console.error('set-env: no .env or .env.template found');
  process.exit(1);
}

const vars = Object.fromEntries(
  readFileSync(source, 'utf8')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#') && line.includes('='))
    .map((line) => {
      const i = line.indexOf('=');
      const value = line.slice(i + 1).trim().replace(/^["']|["']$/g, '');
      return [line.slice(0, i).trim(), value];
    }),
);

if (!vars.API_URL) {
  console.error(`set-env: API_URL is missing in ${source}`);
  process.exit(1);
}

const out = 'src/app/core/config/env.generated.ts';
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/set-env.mjs from ${source}. Do not edit.\n` +
    `export const ENV = { apiUrl: ${JSON.stringify(vars.API_URL)} } as const;\n`,
);
console.log(`set-env: wrote ${out} from ${source}`);
